### ISSUE TITLE
Unable to build video_ludo on mac: 

### ISSUE THREAD

**Issue by simplyakash** [AndreaCatania/video_ludo#1]
Unable to build on mac os 11.6.2, I see that there are no commits in the past 2 years, is this still supposed to build ?,
$cargo run --example video_player
   Compiling ffmpeg-sys v3.4.1
error[E0369]: binary operation `==` cannot be applied to type `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11085:5
      |
11081 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                       --------- in this derive macro expansion
...
11085 |     pub sigev_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^^^^
      |
note: an implementation of `PartialEq<_>` might be missing for `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11042:1
      |
11042 | pub union sigval {
      | ^^^^^^^^^^^^^^^^ must implement `PartialEq<_>`
      = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `sigval` with `#[derive(PartialEq)]`
      |
11042 | #[derive(PartialEq)]
      |

error[E0369]: binary operation `!=` cannot be applied to type `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11085:5
      |
11081 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                       --------- in this derive macro expansion
...
11085 |     pub sigev_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^^^^
      |
note: an implementation of `PartialEq<_>` might be missing for `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11042:1
      |
11042 | pub union sigval {
      | ^^^^^^^^^^^^^^^^ must implement `PartialEq<_>`
      = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `sigval` with `#[derive(PartialEq)]`
      |
11042 | #[derive(PartialEq)]
      |

error[E0277]: the trait bound `sigval: Eq` is not satisfied
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11085:5
      |
11081 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                                  -- in this derive macro expansion
...
11085 |     pub sigev_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^^^^ the trait `Eq` is not implemented for `sigval`
      |
note: required by a bound in `AssertParamIsEq`
     --> /Users/akash/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:316:31
      |
316   | pub struct AssertParamIsEq<T: Eq + ?Sized> {
      |                               ^^ required by this bound in `AssertParamIsEq`
      = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `==` cannot be applied to type `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11164:5
      |
11155 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                       --------- in this derive macro expansion
...
11164 |     pub si_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^
      |
note: an implementation of `PartialEq<_>` might be missing for `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11042:1
      |
11042 | pub union sigval {
      | ^^^^^^^^^^^^^^^^ must implement `PartialEq<_>`
      = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `sigval` with `#[derive(PartialEq)]`
      |
11042 | #[derive(PartialEq)]
      |

error[E0369]: binary operation `!=` cannot be applied to type `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11164:5
      |
11155 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                       --------- in this derive macro expansion
...
11164 |     pub si_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^
      |
note: an implementation of `PartialEq<_>` might be missing for `sigval`
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11042:1
      |
11042 | pub union sigval {
      | ^^^^^^^^^^^^^^^^ must implement `PartialEq<_>`
      = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `sigval` with `#[derive(PartialEq)]`
      |
11042 | #[derive(PartialEq)]
      |

error[E0277]: the trait bound `sigval: Eq` is not satisfied
     --> /Users/akash/virdio/git/video_ludo/target/debug/build/ffmpeg-sys-44b7e5fee866463e/out/bindings.rs:11164:5
      |
11155 | #[derive(Copy, Clone, PartialEq, Eq)]
      |                                  -- in this derive macro expansion
...
11164 |     pub si_value: sigval,
      |     ^^^^^^^^^^^^^^^^^^^^ the trait `Eq` is not implemented for `sigval`
      |

**Comment by AndreaCatania** [comment]
Hello, I don't update this repo from a lot of time. Probably rust is changed a bit from the last time I used it, so this lib needs some maintenance. I don't plan to do it. If you want to use it and you fix those issues you can consider contribute back by opening a PR; I'll review and merge it.
